### ISSUE TITLE
Clumsy revolver

### ISSUE THREAD

**Issue by Iamgoofball** [NTStation/NTstation13#101]
_Issue by **[KazeEspada](https://github.com/KazeEspada)** from Sunday Jul 21, 2013 at 01:03 GMT_
_Originally opened as https://github.com/tgstation/-tg-station/issues/994_

---
##### Which server were you playing on? (REQUIRED!! e.g. TG-Sibyl1, TG-Sibyl2, Badgerstation, Facepunch, Pinkstation, /VG/... etc.)

Sibyl
###### What did you expect to happen?

To hear a click
###### What happened instead?

I shot myself in the foot four times and dropped the gun
###### Why is this bad/What are the consequences?

It cost me my life, after a man came up and beat me to death with my dropped revolver.
##### Steps to reproduce the problem (remember to be specific! Those little details can save us hours of work!):

1.Be clown
2.Get wizard friend
3.Have him summon guns
4.grab revolver
5.shoot it till its empty
6.shoot it again and drop it despite it being unloaded
##### Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?):

Wizard, summon guns.

**Comment by Iamgoofball** [comment]
_Comment by **[Aranclanos](https://github.com/Aranclanos)** from Sunday Jul 21, 2013 at 02:18 GMT_

---

I have no idea what's the issue report about, make better reports please

**Comment by Iamgoofball** [comment]
_Comment by **[Anonus](https://github.com/Anonus)** from Sunday Jul 21, 2013 at 02:22 GMT_

---

He's shooting a revolver(dets or traitors?) that's unloaded while clumsy, and shooting his foot without any ammo.
edit: I think it checks for clumsy on the traitor revolver before it checks for ammo, might be wrong though
2edit: Yup it happens with both revolvers but doesn't seem to do damage
3edit: Holy shit what the fuck this happens with all guns, but it won't do damage if unloaded, only drop the gun.
4edit: and if that wasn't enough, there are multiple checks for clumsy on guns at multiple levels, causing you to shoot yourself in the foot up to 4 times.

**Comment by Iamgoofball** [comment]
_Comment by **[SuperSayu](https://github.com/SuperSayu)** from Sunday Jul 21, 2013 at 02:44 GMT_

---

The gun code (in afterattack()) does a clumsy check before anything else at all, and if the clumsy check succeeds, it will recurse, calling the same code again.  It is unlikely, but not impossible, to pass a 40% probability several times in a row, "shooting yourself in the foot" multiple times with the same shot, even when there is no bullet to be fired.

If however there WERE bullets to be fired you might have legitimately just shot yourself in the foot four times with one shot, spending four bullets for the trouble.

Which is pretty fuckin' special.

**Comment by Iamgoofball** [comment]
_Comment by **[Miauw62](https://github.com/Miauw62)** from Monday Dec 02, 2013 at 18:56 GMT_

---

Does the new gun code fix this?

**Comment by Iamgoofball** [comment]
_Comment by **[Limeliz](https://github.com/Limeliz)** from Wednesday Mar 12, 2014 at 08:27 GMT_

---

Clown killing himself by shooting himself in the foot with an unloaded gun - that got to be a feature!

**Comment by borntohonk** [comment]
Clowns cant use weapons

it's the clown genetic flaw.

**Comment by Iamgoofball** [comment]
Yes but this is an issue with accidentally shooting yourself in the foot with empty guns
