### ISSUE TITLE
Ice cream mancer wouldn't dispense chocolate cones on the shuttle

### ISSUE THREAD

**Issue by Iamgoofball** [NTStation/NTstation13#156]
_Issue by **[Tenebrosity](https://github.com/Tenebrosity)** from Wednesday Oct 02, 2013 at 01:32 GMT_
_Originally opened as https://github.com/tgstation/-tg-station/issues/1491_

---
##### Server Revision:

9c462d1b3a56674cfcc276d6143b13eade6c4461
##### Server:

Basil it's called now apparently
###### What did you expect to happen?

The ice cream mancer would dispense chocolate cones on the shuttle so we could eat ice cream
###### What happened instead?

Pressing the button resulted in nothing happening. There were cones in it to dispense.
###### Why is this bad/What are the consequences?

You can't have ice cream on the shutty.
##### Steps to reproduce the problem:
1. Wait for the shuttle to arrive, making sure your ice cream mancer has cones in it (I encountered this bug trying to dispense chocolate cones)
2. Drag the ice cream mancer onto the shuttle
3. After the shuttle leaves, attempt to dispense chocolate cones 
4. If this is indeed the correct way to reproduce this bug, pressing the chocolate cone button should result in nothing happening
##### Possibly related stuff:

![](http://puu.sh/4FnD3.png)
I noticed this in the connection died and failed to reconnect, so you miss roundstart, pop-up window

**Comment by Iamgoofball** [comment]
_Comment by **[Giacom](https://github.com/Giacom)** from Sunday Oct 06, 2013 at 23:17 GMT_

---

Does it need power ?

**Comment by Iamgoofball** [comment]
_Comment by **[Limeliz](https://github.com/Limeliz)** from Monday Oct 07, 2013 at 11:44 GMT_

---

The connecting part, isn't it a error the hoster has done in the config on the server? The server IP being set to a local IP instead of the public IP, resulting in everyone reconnecting to a local IP on server restart.

**Comment by Iamgoofball** [comment]
_Comment by **[Neerti](https://github.com/Neerti)** from Friday Oct 18, 2013 at 06:10 GMT_

---

Pretty sure the 'related part' was the 'Element icecreamvat not found.' error, not the connect thing under it.

**Comment by Iamgoofball** [comment]
_Comment by **[Tenebrosity](https://github.com/Tenebrosity)** from Wednesday Nov 06, 2013 at 13:20 GMT_

---

@Limeliz Oh, that's interesting

@Neerti He knows, he was just commenting on my complaint

@Giacom Not to my knowledge, it seems strange a movable object would work off APC power

**Comment by Limeliz** [comment]
Whats with the copy-pasting from /tg/?

**Comment by Iamgoofball** [comment]
If we're gonna take their code we should take their issues list as well so we can handle it locally.
