### ISSUE TITLE
Virus bug

### ISSUE THREAD

**Issue by Iamgoofball** [NTStation/NTstation13#233]
_Issue by **[Pathofchaos1](https://github.com/Pathofchaos1)** from Thursday Jan 02, 2014 at 06:23 GMT_
_Originally opened as https://github.com/tgstation/-tg-station/issues/2216_

---

Tg Basil is the server.

I wanted to isolate Eternal Youth from sneezing with synaptizine.

To Get Either Sneezing, or eternal youth Isolated.

I get Cured uncontaminated blood.Injected myself to make sure if I got a hidden disease or something. Didn't happen.

Its bad because if you want to Isolate Eternal Youth A High resistance Symptom. You Can't.

Steps
1. Cold/Rhinovirus Culture blood Into beaker.
2. Plasma to get High level Disease.
3. get Eternal Youth
4. Throw synaptizine to lose the sneezes
5. Get your uncontaminated blood.

**_Edit**_ Same Exact scenario as above. Replace Eternal Youth With Longevity. Trying to isolate the two. Did not give me either Sneezes, or Longevity, but Cured blood again

**Comment by Iamgoofball** [comment]
_Comment by **[Pathofchaos1](https://github.com/Pathofchaos1)** from Thursday Jan 02, 2014 at 06:47 GMT_

---

Addition. Another Virus Eternal Youth, Toxic compensation, Toxic conversion, Weight even. I injected myself with everything... And stepped in contaminated blood Could not get infected. I think the Eternal Youth is bugged in itself. That or I dont understand viruses enough.

**Comment by Iamgoofball** [comment]
_Comment by **[RobRichards1997](https://github.com/RobRichards1997)** from Friday Jan 03, 2014 at 18:43 GMT_

---

I remember pools of blood being changed so they couldn't give people diseases anymore, it was a BIG cause of lag a little while back.

**Comment by Iamgoofball** [comment]
_Comment by **[Pathofchaos1](https://github.com/Pathofchaos1)** from Saturday Jan 04, 2014 at 06:23 GMT_

---

Well the issue is that even if the pool didn't work I injected the virus straight into me The one I commented about, I did it multiple times, a full 30 units of the virus, triple checked in the Machine that each use was full of virus. I will be doing a Fraps run at some point hopefully so you guys can see exactly what I do. Probably going to have some side commentary.. Or not I'm pretty much a fucking mime when it comes to voice

**Comment by Iamgoofball** [comment]
_Comment by **[Giacom](https://github.com/Giacom)** from Tuesday Jan 14, 2014 at 18:03 GMT_

---

OK I think since synaptizine works with just a single unit of it, it is removing a symptom for every unit you add. Not sure how to solve the issue of players mistakenly putting more than one in though.

**Comment by Iamgoofball** [comment]
_Comment by **[Pathofchaos1](https://github.com/Pathofchaos1)** from Wednesday Jan 22, 2014 at 12:33 GMT_

---

Sorry for the late response, Synaptizine froma  dropper of 1 unit still does it, on another note injecting 5 units of synaptizine still only removed one symptom at a time when I had a large amount. Didn't think of it as a bug.

**Comment by Iamgoofball** [comment]
_Comment by **[Giacom](https://github.com/Giacom)** from Wednesday Mar 12, 2014 at 19:30 GMT_

---

Yeah it must be that because it is really hidden it doesn't show up on medical analysers or medical huds.

**Comment by borntohonk** [comment]
Not a bug

eternal youth is +3 stealth

The blood has eternal youth in vars, it just doesnt' show up until you get below +3 stealth, add anything, sneeze, stimulant weight even

and it'll normalize

it's not cured, doesn't show in viro machine after +3 stealth

**Comment by Iamgoofball** [comment]
ah
