### ISSUE TITLE
Secert rooms in mining are now very rare

### ISSUE THREAD

**Issue by Iamgoofball** [NTStation/NTstation13#318]
_Issue by **[Incoming5643](https://github.com/Incoming5643)** from Wednesday Feb 19, 2014 at 01:04 GMT_
_Originally opened as https://github.com/tgstation/-tg-station/issues/2838_

---

Something with how mining works now has made secret rooms almost a nonfactor. They are not spawning according to their basic rules, and the ones that do spawn are very small, like 1x3 or 2x2. You'll be lucky to see more than 1 or 2 rooms in a game (there can be/usually is up to six) and some rounds are completely roomless. 

This really doesn't make a lot of sense because the update also made the east mining field completely solid, so there should be treasure rooms galore over there, even if the west field is too full of tunnels to work.

**Comment by Iamgoofball** [comment]
_Comment by **[Razharas](https://github.com/Razharas)** from Wednesday Feb 19, 2014 at 01:47 GMT_

---

@Ergovisavi

**Comment by Iamgoofball** [comment]
_Comment by **[Ergovisavi](https://github.com/Ergovisavi)** from Wednesday Feb 19, 2014 at 02:15 GMT_

---

Treasure rooms not existing on the eastern asteroid is intentional, after all, adventure favors the bold. The spawn rate on the eastern asteroid is something that I need to look at, yes.

**Comment by Ergovisavi** [comment]
Please do not do things that send emails to me about this codebase. This is already fixed in tgstation.

**Comment by Iamgoofball** [comment]
Sorry about that, I couldn't filter the @personnamehere things out of the comments.

**Comment by Iamgoofball** [comment]
Wity the script, that is.
