### ISSUE TITLE
Removes HoP's helmet

### ISSUE THREAD

**Issue by Iamgoofball** [NTStation/NTstation13#377]
_Issue by **[Ikarrus](https://github.com/Ikarrus)** from Wednesday Mar 12, 2014 at 15:00 GMT_
_Originally opened as https://github.com/tgstation/-tg-station/pull/3058_

---

What it says on the tin. Removes the helmet from spawning HoPs and the one in his locker. The intent was to reduce the perception that the HoP is a combat-oriented role and further discourage and make more obvious of HoPs who powergame/HoPcurity.

Questions or concerns are welcome.

---

_**[Ikarrus](https://github.com/Ikarrus)** included the following code: https://github.com/tgstation/-tg-station/pull/3058/commits_

**Comment by Iamgoofball** [comment]
_Comment by **[Nienhaus](https://github.com/Nienhaus)** from Wednesday Mar 12, 2014 at 15:02 GMT_

---

Ian is the only on in that office who needs a helmet and armour. :+1:

**Comment by Iamgoofball** [comment]
_Comment by **[fleure](https://github.com/fleure)** from Wednesday Mar 12, 2014 at 15:02 GMT_

---

Let me just grab my popcorn

**Comment by Iamgoofball** [comment]
_Comment by **[EuroNumbers](https://github.com/EuroNumbers)** from Wednesday Mar 12, 2014 at 15:04 GMT_

---

Leaving armour in the locker would be wise though, since well HoP is second in command and always have been, some emergency protection in case of shit going down is a good idea. 

I'm all for him spawning without armour though. The days of Commando HoP should be over.

**Comment by Iamgoofball** [comment]
_Comment by **[Ikarrus](https://github.com/Ikarrus)** from Wednesday Mar 12, 2014 at 15:05 GMT_

---

I'd like to think that, in case of emergency, the HoP should just walk down to security and take one of theirs. An emergency is, after all, a legitimate reason to take armor.

**Comment by Iamgoofball** [comment]
_Comment by **[fleure](https://github.com/fleure)** from Wednesday Mar 12, 2014 at 15:05 GMT_

---

Though my two cents: I actually think you're right. People often play HoP like he's the head of security or some kind of station batman, which he ain't. You can still request gear from the warden or HoS, too.

RIP armoured Ian, though.

**Comment by Iamgoofball** [comment]
_Comment by **[Ikarrus](https://github.com/Ikarrus)** from Wednesday Mar 12, 2014 at 15:07 GMT_

---

I can't imagine any officer denying a request from the HoP for armor for Ian. Unless they are literally Hitler.

**Comment by Iamgoofball** [comment]
_Comment by **[EuroNumbers](https://github.com/EuroNumbers)** from Wednesday Mar 12, 2014 at 15:12 GMT_

---

Well Sec is often called the SS, so yes, they're like little Hitlers, running around the station.

I'm still on the fence about it being removed from the locker. I'm all for it being removed from HoP.

:8ball: Reply hazy. Try again later.

**Comment by Iamgoofball** [comment]
_Comment by **[Atskadan](https://github.com/Atskadan)** from Wednesday Mar 12, 2014 at 15:19 GMT_

---

removing security channel from the headset didnt stop people from stealing one at roundstart
all this will do is mean security gets even less equipment

**Comment by Iamgoofball** [comment]
_Comment by **[Aranclanos](https://github.com/Aranclanos)** from Wednesday Mar 12, 2014 at 15:20 GMT_

---

okay okay how about removing the helmet but leaving the body armor, eh?

**Comment by Iamgoofball** [comment]
_Comment by **[Ikarrus](https://github.com/Ikarrus)** from Wednesday Mar 12, 2014 at 15:22 GMT_

---

@Atskadan Unlike radios, armor is highly visible and makes it very obvious what he did. Not to mention taking a sec key every round is pretty shitty. I don't believe "Because people will powergame anyway" is a good reason to not do something against it. I don't believe security ever has a shortage of armor, either, considering they have 8 spare sets.

@Aranclanos Why one but not the other?

**Comment by Iamgoofball** [comment]
_Comment by **[Aranclanos](https://github.com/Aranclanos)** from Wednesday Mar 12, 2014 at 15:31 GMT_

---

well I believe the helmet is what gives them the "officer" feel. Plus some people like the new armor and the swag factor is impurrtant.
Just for the record, when I play HoP I leave the armor and helmet on the locker. (and take jumpsuits from places that I shouldn't be but I'm corrupt because #swag)

**Comment by Iamgoofball** [comment]
_Comment by **[Ikarrus](https://github.com/Ikarrus)** from Wednesday Mar 12, 2014 at 15:32 GMT_

---

I can see how that would work. I'd be fine with it, especially if people make a new sprite for the vest that looked less military.

**Comment by Iamgoofball** [comment]
_Comment by **[Aranclanos](https://github.com/Aranclanos)** from Wednesday Mar 12, 2014 at 15:33 GMT_

---

oh and the fact that a lot of people will be upset and we don't need the drama right now

**Comment by Iamgoofball** [comment]
_Comment by **[Ikarrus](https://github.com/Ikarrus)** from Wednesday Mar 12, 2014 at 15:35 GMT_

---

Oh boy, -Political- reasons. If it's that much of a concern for you then I don't have anything to say about it.

**Comment by Iamgoofball** [comment]
_Comment by **[VistaPOWA](https://github.com/VistaPOWA)** from Wednesday Mar 12, 2014 at 15:35 GMT_

---

How about you just re-use the old armor and helmet sprites with lowered protection stats?
Makes sense that HoP gets surplus security equipment, if he even gets ANY.

**Comment by Iamgoofball** [comment]
_Comment by **[Aranclanos](https://github.com/Aranclanos)** from Wednesday Mar 12, 2014 at 15:38 GMT_

---

oh cmon don't be like that, I gave you real reasons and then a plus. If you want ignore the plus but not the whole thing.

**Comment by Iamgoofball** [comment]
_Comment by **[Malkevin](https://github.com/Malkevin)** from Wednesday Mar 12, 2014 at 15:39 GMT_

---

HoP needs a hat, I'd say something inspired by Papers, Please

**Comment by Iamgoofball** [comment]
_Comment by **[EuroNumbers](https://github.com/EuroNumbers)** from Wednesday Mar 12, 2014 at 15:42 GMT_

---

Well Ikarrus, taking players' toys make them upset. Give them a new toy to distract them while you take away their old toys... never fails.

**Comment by Iamgoofball** [comment]
_Comment by **[Ikarrus](https://github.com/Ikarrus)** from Wednesday Mar 12, 2014 at 15:42 GMT_

---

If I had offended you Aran, I apologize. That was not the intent of my reply.

**Comment by Iamgoofball** [comment]
_Comment by **[GunHog](https://github.com/GunHog)** from Wednesday Mar 12, 2014 at 15:52 GMT_

---

MUST we do this? :-1:  No self respecting HoS would let the HoP trot around acting as Security, unless his team is so thin that he has to resort to letting potential antags join up. It is better to give him resprited armor so he looks more like an executive, and not an officer.

We are talking about a guy that walks around with all-access here. Leaving him naked and unsatisfied could have quite a few consequences. Assistants and clowns will no longer consider him a threat, and the lure of all-access is too juicy to ignore. You could see the return of Guncargo, for when the HoS refuses to share his.gear, and the HoP feels too weak with only his E-gun.

Let us avoid screwing over the guy with the all-access ID, eh? We do NOT need the HoP looting things he should already have.

**Comment by Iamgoofball** [comment]
_Comment by **[Miauw62](https://github.com/Miauw62)** from Wednesday Mar 12, 2014 at 15:55 GMT_

---

Yeah, I think that we really should keep the armor in the locker. The HoP
spawning with armor is a little silly, though. (Also the bare HoP's
jumpsuit sort of looks like shit so we should give him a fancy parade tunic
or so instead)

**Comment by Iamgoofball** [comment]
_Comment by **[Ikarrus](https://github.com/Ikarrus)** from Wednesday Mar 12, 2014 at 15:58 GMT_

---

These are valid concerns and you make a very fair point, gun hog. Would it be preferable for you to just have him spawn without it, but store it in his locker?  We could always change the sprites later.

**Comment by Iamgoofball** [comment]
_Comment by **[VistaPOWA](https://github.com/VistaPOWA)** from Wednesday Mar 12, 2014 at 15:59 GMT_

---

Yes.

**Comment by Iamgoofball** [comment]
_Comment by **[Nienhaus](https://github.com/Nienhaus)** from Wednesday Mar 12, 2014 at 16:00 GMT_

---

If anything he doesn't really need a helmet.

**Comment by Iamgoofball** [comment]
_Comment by **[Aranclanos](https://github.com/Aranclanos)** from Wednesday Mar 12, 2014 at 16:00 GMT_

---

it's the same if you spawn it on the locker, the person will take it, as their already take the sunglasses, flash and gun. You're just adding more little tasks to the roundstart gearup.

**Comment by Iamgoofball** [comment]
_Comment by **[Malkevin](https://github.com/Malkevin)** from Wednesday Mar 12, 2014 at 16:08 GMT_

---

Let's be honest here, 99% of HoPs give themselves all access as part of their initial round start warm up, they're also in charge of the department that is responsible for ordering more equipment.

## They're either going to raid cargos sec locker or order an armor crate themselves (which of course leaves a surplus vest and helmet if the HoP takes one for himself and one for Ian)

-----Original Message-----

**Comment by Iamgoofball** [comment]
_Comment by **[Malkevin](https://github.com/Malkevin)** from Wednesday Mar 12, 2014 at 16:17 GMT_

---

## Oh, and also, no sec is going to bother tackling a hop sat in his office wearing stolen armor because a certain few people decided to revert the hop office back to der corgi bunker

-----Original Message-----
From: akenworthy87@gmail.com
Date: Wed, 12 Mar 2014 16:08:01 
To: tgstation/-tg-stationreply@reply.github.com
Reply-To: akenworthy87@gmail.com
Subject: Re: [-tg-station] Removes HoP's armor and helmet (#3058)

Let's be honest here, 99% of HoPs give themselves all access as part of their initial round start warm up, they're also in charge of the department that is responsible for ordering more equipment.

## They're either going to raid cargos sec locker or order an armor crate themselves (which of course leaves a surplus vest and helmet if the HoP takes one for himself and one for Ian)

-----Original Message-----

**Comment by Iamgoofball** [comment]
_Comment by **[Ikarrus](https://github.com/Ikarrus)** from Wednesday Mar 12, 2014 at 16:23 GMT_

---

Simply removing the helmet could also do the trick. It wouldn't make him look like a trooper, but still maintain defense values befitting of someone with functionally-all-access. I like it more than just keeping it in his locker, vis a vis aran's point.

**Comment by Iamgoofball** [comment]
_Comment by **[Aranclanos](https://github.com/Aranclanos)** from Wednesday Mar 12, 2014 at 16:28 GMT_

---

yeah there we go apc destroyed mission accomplished

**Comment by Iamgoofball** [comment]
_Comment by **[Ikarrus](https://github.com/Ikarrus)** from Wednesday Mar 12, 2014 at 16:28 GMT_

---

I've updated the PR to only remove the security helmet, please let me know if this is more acceptable.

**Comment by Aranclanos** [comment]
ahhh stop pinging me in a million of issues

**Comment by Iamgoofball** [comment]
sorry, there was no way to tell the script "hey fuck off and don't add the @person things".

**Comment by Aranclanos** [comment]
what's even the point of copying all issues, that will just make a mess

**Comment by Iamgoofball** [comment]
we were getting yelled at to bring over the issues list

**Comment by Aranclanos** [comment]
...by who?

**Comment by Aranclanos** [comment]
the idea of having useful comments going to waste because they have to choose in what branch they have to help in the issue list doesn't make any sense. It only generates problems and lack of organization.

**Comment by Iamgoofball** [comment]
Ah, good point.

**Comment by Aranclanos** [comment]
so yeah you should close them all
