### ISSUE TITLE
Virus stays at 1/5

### ISSUE THREAD

**Issue by Iamgoofball** [NTStation/NTstation13#380]
_Issue by **[Marflowerose](https://github.com/Marflowerose)** from Wednesday Mar 12, 2014 at 22:44 GMT_
_Originally opened as https://github.com/tgstation/-tg-station/issues/3061_

---

Seemingly random viruses stays at 1/5 stages for some people.

**Comment by theOperand** [comment]
pls remove the "originally opened as" things jesus we don't need a link on literally every single issue in tgstation.
