### ISSUE TITLE
compiling bug

### ISSUE THREAD

**Issue by jellopudding** [NTStation/NTstation13#387]
_note: I closed this because I accidentally opened it without any description_
I'm trying to compile the SS13 code but it gives me this:
"tgstation.dmb - 100 errors, 0 warnings (max count reached)"

Revision that this bug was encountered on:
NTStation 13 - March 23, 2014 2:40 pm Pacific

source code of /tg/station 

Problem Description
compiling automatically stopped with the error:
"tgstation.dmb - 100 errors, 0 warnings (max count reached)"

the code was not compliantly finished compiling

Steps to reproduce the problem
1. download code
2. unzip
3. try to compile without messing with anything

Possibly related stuff:
I may be doing something wrong myself
code from console (warning very long):
loading tgstation.dme
loading interface\skin.dmf
code__HELPERS\icons.dm:665:error: BLEND_DEFAULT: undefined var
code__HELPERS\icons.dm:730:error: I/:/alpha: undefined var
code__HELPERS\icons.dm:734:error: BLEND_OVERLAY: undefined var
code__HELPERS\type2type.dm:271:error: BLEND_MULTIPLY: undefined var
code__HELPERS\type2type.dm:272:error: BLEND_ADD: undefined var
code__HELPERS\type2type.dm:273:error: BLEND_SUBTRACT: undefined var
code_onclick\hud\human.dm:303:error: BLEND_MULTIPLY: undefined var
code_onclick\hud\human.dm:311:error: BLEND_ADD: undefined var
code_onclick\hud\hud.dm:19:error: BLEND_MULTIPLY: undefined var
code_onclick\hud\hud.dm:66:error: BLEND_MULTIPLY: undefined var
code_onclick\hud\hud.dm:72:error: BLEND_MULTIPLY: undefined var
code_onclick\hud\hud.dm:79:error: BLEND_MULTIPLY: undefined var
code\modules\mob\living\carbon\human\life.dm:149:error: animate: undefined proc
code\modules\mob\living\carbon\human\life.dm:150:error: animate: undefined proc
code\modules\mob\living\carbon\human\life.dm:941:error: animate: undefined proc
code\modules\mob\living\carbon\human\life.dm:942:error: animate: undefined proc
code\modules\mob\living\carbon\human\life.dm:983:error: BLEND_OVERLAY: undefined var
code\modules\mob\living\carbon\human\life.dm:1032:error: BLEND_ADD: undefined var
code\modules\mob\living\carbon\update_icons.dm:6:error: transform: undefined var
code\modules\mob\living\carbon\update_icons.dm:6:error: matrix: undefined proc
code\modules\mob\living\carbon\update_icons.dm:25:error: EASE_IN: undefined var
code\modules\mob\living\carbon\update_icons.dm:25:error: EASE_OUT: undefined var
code\modules\mob\living\carbon\update_icons.dm:25:error: animate: undefined proc
code\modules\mob\living\death.dm:48:error: alpha: undefined var
code__HELPERS\matrices.dm:3:error: Turn: undefined proc
code\game\area\areas.dm:43:error: blend_mode: undefined var
code\game\area\areas.dm:43:error: BLEND_MULTIPLY: undefined var
code\modules\hydroponics\grown.dm:30:error: transform: undefined var
code\modules\reagents\reagent_containers\food\snacks.dm:655:error: alpha: undefined var
code\modules\reagents\reagent_containers\food\snacks.dm:2487:error: color: undefined var
code\modules\reagents\reagent_containers\food\snacks.dm:2497:error: color: undefined var
code\modules\reagents\reagent_containers\food\snacks.dm:2507:error: color: undefined var
code\modules\reagents\reagent_containers\food\snacks.dm:2517:error: color: undefined var
code\modules\reagents\reagent_containers\food\snacks.dm:2527:error: color: undefined var
code\modules\reagents\reagent_containers\food\snacks.dm:2537:error: color: undefined var
code\modules\reagents\reagent_containers\food\snacks.dm:769:error: alpha: undefined var
code\modules\hydroponics\growninedible.dm:26:error: transform: undefined var
code\modules\hydroponics\growninedible.dm:32:error: transform: undefined var
code\modules\events\ninja.dm:2208:error: U.alpha: undefined var
code\modules\events\ninja.dm:2220:error: U.alpha: undefined var
code\modules\clothing\head\misc_special.dm:127:error: color: undefined var
code\modules\clothing\head\misc_special.dm:136:error: color: undefined var
code\modules\paperwork\photography.dm:179:error: A.blend_mode: undefined var
code\game\machinery\kitchen\smartfridge.dm:264:error: S.color: undefined var
code\game\objects\effects\decals\crayon.dm:31:error: color: undefined var
code\game\mecha\mecha_wreckage.dm:106:error: color: undefined var
code\modules\recycling\disposal-construction.dm:76:error: alpha: undefined var
code\game\mecha\combat\reticence.dm:17:error: color: undefined var
code__HELPERS\icons.dm:628:error: A.blend_mode: undefined var
code__HELPERS\icons.dm:633:error: A.alpha: undefined var
code__HELPERS\icons.dm:665:error: A.blend_mode: undefined var
code__HELPERS\icons.dm:668:error: A.blend_mode: undefined var
code__HELPERS\icons.dm:676:error: copy.color: undefined var
code__HELPERS\icons.dm:676:error: A.color: undefined var
code__HELPERS\icons.dm:677:error: copy.alpha: undefined var
code__HELPERS\icons.dm:677:error: A.alpha: undefined var
code__HELPERS\icons.dm:678:error: copy.blend_mode: undefined var
code__HELPERS\icons.dm:754:error: A.color: undefined var
code__HELPERS\icons.dm:755:error: A.color: undefined var
code__HELPERS\icons.dm:756:error: A.alpha: undefined var
code__HELPERS\icons.dm:757:error: A.alpha: undefined var
code_onclick\hud\hud.dm:19:error: druggy.blend_mode: undefined var
code_onclick\hud\hud.dm:66:error: O.blend_mode: undefined var
code_onclick\hud\hud.dm:72:error: O.blend_mode: undefined var
code_onclick\hud\hud.dm:79:error: O.blend_mode: undefined var
code\game\objects\effects\effect_system.dm:540:error: smoke.color: undefined var
code\modules\mob\living\carbon\human\life.dm:983:error: I.blend_mode: undefined var
code\modules\mob\living\carbon\human\life.dm:1032:error: I.blend_mode: undefined var
code\modules\mob\living\carbon\human\life.dm:1047:error: black.color: undefined var
code\modules\mob\living\carbon\human\update_icons.dm:162:error: img_facial_s.color: undefined var
code\modules\mob\living\carbon\human\update_icons.dm:175:error: img_hair_s.color: undefined var
code\modules\mob\living\carbon\human\update_icons.dm:225:error: img_eyes_s.color: undefined var
code\modules\mob\living\carbon\human\update_icons.dm:452:error: standing.color: undefined var
code\modules\mob\living\carbon\human\update_icons.dm:452:error: head.color: undefined var
code\modules\mob\living\carbon\human\update_icons.dm:453:error: standing.alpha: undefined var
code\modules\mob\living\carbon\human\update_icons.dm:453:error: head.alpha: undefined var
code\modules\mob\living\simple_animal\hostile\mushroom.dm:53:error: cap_living.color: undefined var
code\modules\mob\living\simple_animal\hostile\mushroom.dm:54:error: cap_dead.color: undefined var
code\modules\reagents\reagent_containers\spray.dm:52:error: D.color: undefined var
code\modules\reagents\reagent_containers\spray.dm:189:error: D.color: undefined var
code\modules\reagents\reagent_containers\glass.dm:139:error: filling.color: undefined var
code\modules\reagents\reagent_containers\syringes.dm:195:error: filling.color: undefined var
code\game\objects\items\weapons\paint.dm:87:error: target.color: undefined var
code\game\objects\items\weapons\paint.dm:97:error: target.color: undefined var
code\game\objects\items\weapons\paint.dm:97:error: target.color: undefined var
code\game\objects\items\weapons\paint.dm:98:error: target.color: undefined var
code\game\objects\items\weapons\paint.dm:98:error: target.color: undefined var
code\game\objects\items\weapons\paint.dm:97:error: initial: bad variable
code\game\objects\items\weapons\paint.dm:98:error: initial: bad variable
code\modules\clothing\clothing.dm:182:error: I.transform: undefined var
code\modules\clothing\clothing.dm:253:error: hastie.transform: undefined var
code\modules\paperwork\photography.dm:185:error: T.blend_mode: undefined var
code\game\gamemodes\cult\ritual.dm:213:error: src.color: undefined var
code\game\gamemodes\cult\ritual.dm:216:error: src.color: undefined var
code\game\gamemodes\cult\ritual.dm:226:error: src.color: undefined var
code\game\gamemodes\cult\ritual.dm:236:error: src.color: undefined var
code\game\gamemodes\cult\ritual.dm:243:error: src.color: undefined var
code\game\gamemodes\cult\ritual.dm:247:error: src.color: undefined var
code\game\gamemodes\cult\ritual.dm:254:error: src.color: undefined var
code\game\gamemodes\cult\ritual.dm:258:error: src.color: undefined var
code\game\gamemodes\cult\ritual.dm:262:error: src.color: undefined var
tgstation.dmb - 100 errors, 0 warnings (max count reached)

**Comment by Iamgoofball** [comment]
You're using the wrong BYOND Dreammaker version.

You need to use 504.

**Comment by jellopudding** [comment]
ok 
thanks for the help
