### ISSUE TITLE
Placing new windows has the new window's icon_state be null.

### ISSUE THREAD

**Issue by Neerti** [NTStation/NTstation13#423]
This happens live on Artyom.  It results in the window turning into a table with a smile due to the lack of an icon_state to tell the window to look like a window.

**Comment by RemieRichards** [comment]
Now doubt due to Plasma windows, only change to windows I can recall.

**Comment by Iamgoofball** [comment]
startoad probably didn't port the code properly, he must of used his own version instead of the fixed up BS12 version I did

I'll look into it

**Comment by Atskadan** [comment]
speaking of plasma windows we should probably actually use them

**Comment by Iamgoofball** [comment]
they are p. strong, let's not use them yet until I make time to fix them and make them work

**Comment by ghost** [comment]
This can be closed, it's been fixed.
