### ISSUE TITLE
You can put GRABS into the many item sandwiches.

### ISSUE THREAD

**Issue by RemieRichards** [NTStation/NTstation13#449]
- Revision: Up to date as of 15/04/2014, However associated code has not been touched since
- Problem Description: You can put Grabs into the infinite super sandwiches
- What did you expect to happen: Grabs are not a "Real" Item, They should not go into sandwiches
- What happened instead? How is what happened different from what you expected:
  It's not REAL, it shouldn't go into a sandwich
- Why is this bad/What are the consequences? Why do you think this is an important issue: Sandwich size competitions can be forged now, More items may result in more nutrient rich sandwiches
- Steps to reproduce the problem: The most important section. Review everything you did leading up to causing the issue: Grab a mob, click on sandwich with the Grab "item"
- Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Anything else you can tell us: The gamemode was Extended because muh testings.

**Comment by drynwyn** [comment]
I bet you can make armblade sandwiches.

#454 will fix this

**Comment by Iamgoofball** [comment]
Working as intended.

(not)
