### ISSUE TITLE
Windows Placed on Grilles Appear as Happy Tables

### ISSUE THREAD

**Issue by Yakk** [NTStation/NTstation13#464]
How to replicate:
1. Find or build grille out of metal rods.
2. Take glass in hand and click grille
3. Receive smiley table instead of glass window pane placed appropriately on grille.
![artyom fortification 2014-04-18 181248](https://cloud.githubusercontent.com/assets/4669135/2746465/f710aa18-c747-11e3-89ba-5539386a5be8.png)

Note that this only works on windows placed directly on to grilles by players. You can put down windows anywhere else not a grille without this happening.

E: Git is hard and there's already an issue for this by Neerti. Oops!

**Comment by Atskadan** [comment]
duplicate issue
