### ISSUE TITLE
Disablers

### ISSUE THREAD

**Issue by Skorvold** [NTStation/NTstation13#480]
Disablers break windows that are fired at.

**Comment by Atskadan** [comment]
ill fix it sometime
do people actually use disablers? i dont think theyre very useful, are they?

**Comment by drynwyn** [comment]
Only when they can't get something better. 3-hit takedown and 20 shots is pretty meh.

**Comment by ghost** [comment]
Disabler projectiles do 1 damage. I think people would use them more if they were easy as fuck to make by rnd or didn't come in lockboxes, people could essentially use them for self defense pretty easily while traitors/grey tide wouldn't do much with them, and if they did, they'd be rekt by sec's tasers.

**Comment by Atskadan** [comment]
not really an issue
