### ISSUE TITLE
You don't have any bugs

### ISSUE THREAD

**Issue by Incoming5643** [NTStation/NTstation13#5]
if you're taking our code you're taking our problems too. I don't know if there's any sound way to port https://github.com/tgstation/-tg-station/issues?state=open over here but you should really do something. 

Especially with open master access you can expect to quickly move past bugs without resolving them if no one notices until they actually try to run a live server.

**Comment by Boggart** [comment]
[This](https://github.com/IQAndreas/github-issues-import) or [this](https://github.com/collective/collective.developermanual/blob/master/gh-issues-import.py) may work. [Source](https://stackoverflow.com/questions/9720718/how-do-i-move-an-issue-on-github-to-another-repo)

If not, one of them may be able to be hacked into a working form.

**Comment by Iamgoofball** [comment]
Ima give this a try then.

**Comment by Iamgoofball** [comment]
Alright there's a script running to port the issues over now
