### ISSUE TITLE
[My Own Fault] Long-Range singulo forming with BoH

### ISSUE THREAD

**Issue by drynwyn** [NTStation/NTstation13#518]
You can click a bag of holding with another bag of holding, run away, then click yes on the confirmation window.
My own fault, will fix as soon as I figure out the git witchcraft needed to update my fork's master branch.

**Comment by Iamgoofball** [comment]
ahahahahaha

best bug 2014

**Comment by Atskadan** [comment]
right click > pull > select origin/master (or whatever you named the ntstation repo link to) > pull
updates ur stuf

**Comment by drynwyn** [comment]
Fixed, close this.
