### ISSUE TITLE
Using the scrying orb permanently removes all spells.

### ISSUE THREAD

**Issue by WJohn** [NTStation/NTstation13#556]
How to reproduce:
1. Spawn yourself as wizard
2. Get your spells and a scrying orb
3. Use scrying orb
4. See all spells are gone when you return to your body
5. Cry as the crew fists you for having no spells

Why is this bad?
Do I even have to tell you why.

**Comment by Iamgoofball** [comment]
shit man that's bad

will look into Soon (tm)

**Comment by drynwyn** [comment]
It's a result of tying spells to the mind, I think. Spells also vanish if you are dead and leave then return to your body.

**Comment by Kraseo** [comment]
Cannot reproduce.

**Comment by Iamgoofball** [comment]
yeah I think we fixed this with the tg merge
