### ISSUE TITLE
Space Pulling Runtime

### ISSUE THREAD

**Issue by RemieRichards** [NTStation/NTstation13#564]
runtime error: Cannot read null.pulling
proc name: Entered (/turf/space/Entered)
  source file: space.dm,99
  usr: 0
  src: space (248,153,1) (/turf/space)
  call stack:
space (248,153,1) (/turf/space): Entered(the bullet (/obj/item/projectile/bullet), space (247,153,1) (/turf/space))
the bullet (/obj/item/projectile/bullet): Move(space (248,153,1) (/turf/space), 4)
the bullet (/obj/item/projectile/bullet): Move(space (248,153,1) (/turf/space), 4)
the bullet (/obj/item/projectile/bullet): process()

@Ikarrus !

**Comment by ghost** [comment]
Welp. I'll investigate when I have time. Likely in the next couple of days.

**Comment by RemieRichards** [comment]
Good, just drawing it to your attention.
