### ISSUE TITLE
Artyom is having huge lagspikes, and this is why

### ISSUE THREAD

**Issue by Neerti** [NTStation/NTstation13#576]
http://puu.sh/8Pc16.png

Something is causing the master controller to have extreme spikes.

What exactly is doing it, I don't know, but we should do everything we can to figure out what, because the lag is really, really bad, and it's on a live server.

**Comment by Neerti** [comment]
The gamemode was Nuclear,

A minor lagspike lasting ten seconds occurred at roundend, with the master controller spiking again.

**Comment by RemieRichards** [comment]
Are we certain as to which of the two entities is causing this?
Is it the MC itself? or is it the Nuclear gamemode?

Can you get me some information from other rounds? to see if it's not Nuclear?
When did it start occurring? to the best of your or another's Knowledge?

The biggest change to the Gamemodes is my own, when I cleaned up the Colon's on Wednesday, But looking at it it really shouldn't have increased lag, Yes I replaced a few bad "ticker.mode.name==" checks with Proper istypes() but that really shouldn't causes issues, it's still comparing a variable (in this case the type var)

Edit: Looking at the MC, it makes the Ticker process, which makes it's mode process, and Nuclear's process seems to be the default "return 0" so I'm not 100% certain it's Nuclear itself.

**Comment by Neerti** [comment]
Its probably not ops. 
Idk whats causing it.

**Comment by Atskadan** [comment]
definitely not just nuke
its been lagging horribly for a while now

**Comment by Atskadan** [comment]
hey its almost as if github automatically closes issues when you merge pr's that say "fixes #number"
