### ISSUE TITLE
RD doesn't spawn with an internals box

### ISSUE THREAD

**Issue by themados** [NTStation/NTstation13#591]
The last 3-4 times I have chosen the RD i have ot spawned with an internals box, this doesn't happen with any other job.

**Comment by ghost** [comment]
It's only in the satchel. I changed RD to spawn with the proper job-flavored science satchel a while ago as well as a few other jobs I cannot recall but my original PR is here: 

https://github.com/NTStation/NTstation13/pull/534

I'm not exactly sure where the spawn-internals box code is and but the solution is to use a backpack until it is fixed for now.

**Comment by themados** [comment]
I do use the backpack and I have never use the satchel. Unless you mean that i should be using the satchel?
