### ISSUE TITLE
Engineering borg stacks disappear when you 'use them up'

### ISSUE THREAD

**Issue by ghost** [NTStation/NTstation13#634]
For example, make yourself an engineering borg and place lattices in space, after you 'use up' 50 rods the icon will just disappear and putting it back into your storage makes it inaccessible.

Is this an issue on sybil as well?

**Comment by Neerti** [comment]
Does recharging make it appear again?

**Comment by ghost** [comment]
I'm not sure, I mean, I could still place them after I 'ran out', the icon just disappeared. It took up a space in my inventory too. I thought borgs were meant to have unlimited stacks but used energy placing them, so that's what's worrying.

**Comment by Atskadan** [comment]
I think you're only supposed to get a limited amount, but they return when you recharge.

**Comment by ghost** [comment]
Cheers, I looked at the code to confirm.
