### ISSUE TITLE
Rolling down a Security jumpsuit and back up again causes "SUIT" sprite

### ISSUE THREAD

**Issue by RemieRichards** [NTStation/NTstation13#643]
The sprite disappears and shows the "SUIT" sprite. May be more than just the Sec jumpsuit

These jumpsuits when rolled down, work fine. but once rolled up again their "icon_color" var becomes null, thus they display the "SUIT" icon

this is:
/obj/item/clothingunder/rank/security/cargo
/obj/item/clothingunder/rank/security/science
/obj/item/clothingunder/rank/security/engi

etc, the Subtypes.

Now idea if the /tg/ merge broke this or if it was always there.

**Comment by Atskadan** [comment]
It was there before the merge. I've seen it on sec jumpsuits. They're permanently ruined, so if you want to prank security, you can roll down all their jumpsuits and they'll be naked.

**Comment by RemieRichards** [comment]
It isn't sec jumpsuits Miggles, it's the subtypes only. Which spawn on Department sec officers, the bug is isolated to them.

**Comment by Atskadan** [comment]
remie just because youre a coder doesnt mean you have to ruin my fun :(

**Comment by RemieRichards** [comment]
Honk :)

**Comment by Atskadan** [comment]
#671 fixes this

**Comment by ghost** [comment]
Well no it doesn't fix it. It just blocks all security from rolling down their jumpsuits, including the hoss and warden jumpsuits. It doesn't happen often enough for it to be a thing, and sec has the new camo pants if they want to go shirtless/tank top shitcurity anyway.

**Comment by Atskadan** [comment]
its a fix in the traditional sense, like with dogs
just snip it out
