### ISSUE TITLE
Cigarettes can be adjusted like masks.

### ISSUE THREAD

**Issue by Atskadan** [NTStation/NTstation13#672]
You try pushing the lit cigarette out of the way, but it is very uncomfortable and you look like a fool. You push it back into place.

**Comment by Iamgoofball** [comment]
yes, because it's a mask slot item.

this really doesn't need an issue report

unless you'd like code to check if what's in your mouth is a cigarette to give different flavor text.

**Comment by Atskadan** [comment]
Yes I know why it happens that's why I said it isn't a bug
Knowing the cause doesn't make it not a bad thing

**Comment by Iamgoofball** [comment]
what do you want it to do then? flavor text wise, anyways

**Comment by Atskadan** [comment]
not display a message? using the cigarette is supposed to stomp it into the ground

**Comment by ghost** [comment]
someone who can figure out cigarette code can make it so using a cigarette toggles it up so you can put it behind your ear when it's unlit, but stomps it out when it's lit, just a suggestion.

**Comment by Atskadan** [comment]
why would you want that

**Comment by Iamgoofball** [comment]
who wouldn't want to look badass with a cigar behind their ear?

**Comment by Atskadan** [comment]
is putting cigars/cigarettes behind your ear a thing?
i know people do it with pencils but i've never seen someone do it with smokes

**Comment by ike709** [comment]
But that would give people ear cancer!

**Comment by ghost** [comment]
It's a greaser/mechanic trope you'll see in a lot of 1950s shit probably

Would go great with leather jackets

Tunnel snakes rule
