### ISSUE TITLE
Energy gun sprites break

### ISSUE THREAD

**Issue by Neerti** [NTStation/NTstation13#675]
http://puu.sh/9cIW8/c074e73d1c.png

I got an adminhelp saying their egun 'disappeared' after switching it to kill mode.  I check and it was still in his hand, just invisible because the icon_state borked up.

I suspect this has to do with the recent change but I'm not exactly sure how it would happen if it was just a sprite change?

The correct icon_state is [icon_state]100, [icon_state]75, etc, for each charge level.  It was at 1500 which no sprite exists for, so it appeared blank.

**Comment by ghost** [comment]
Yeah the code for these was literally untouched, did he get EMP'd or anything? I'm not sure why it would do that.

**Comment by ghost** [comment]
I possibly fixed it here: https://github.com/NTStation/NTstation13/pull/671

But let's leave this issue up just in case.
