### ISSUE TITLE
Poster Error

### ISSUE THREAD

**Issue by ghost** [NTStation/NTstation13#692]
I found a poster near the black market; examining told me to report the issue here.
<a href="http://imgur.com/d6MFwuU"><img src="http://i.imgur.com/d6MFwuU.png" title="Hosted by imgur.com"/></a>
The item was called "No. The plating" and when placed back down it rendered nothing. There were some other posters like it.

**Comment by JStheguy** [comment]
Yeah, it turns out subtypes or something fucked up pre-posted posters.
They've been removed recently until we can figure out exactly what is wrong with them, I guess the server hasn't updated yet.

**Comment by ghost** [comment]
Someone close this.
