### ISSUE TITLE
Engineers No Longer Know Door Wires

### ISSUE THREAD

**Issue by Yakk** [NTStation/NTstation13#694]
Revision: NTstation, whateverone Artytom was running as of June 6.
Problem Description: Engineers do not have knowledge of door wires in their notes.
What did you expect to happen?: Door wires to show up when I clicked notes
What happened instead?: Nothing
Why is this bad/What are the consequences?: I'm okay with it but an entire feature disappeared so that's maybe bad. 
Steps to reproduce the problem: Be engineer, click notes.
Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Maybe related to merging stuff from /tg/station?

**Comment by RemieRichards** [comment]
/tg/ merge probably removed this yeah.
