### ISSUE TITLE
pens giving illegal tech research levels

### ISSUE THREAD

**Issue by Tokiko1** [NTStation/NTstation13#709]
This has been known to occur for a while now but I only recently figured out how to reproduce this:
1. Get a regular pen.
2. Try to insert it into the DA. It will not work because it's not a parapen. (Optional)
3. Stab something with the pen.
4. Insert the pen in the DA and notice that it now appears to be a parapen.

**Comment by ghost** [comment]
I wonder just how many people have been put into the permabrig over this.

Enjoy your free illegal tech 5/6 while it lasts guys.

**Comment by Lumipharon** [comment]
I know that the parapens you get from a spec op crate can't be decon'd. Haven't tried stabbing anyone with them first however. Is this intended?

**Comment by ghost** [comment]
Any pen can be deconed if you stab someone with them first. Same applies to parapens.

I think the code denotes that if you're stabbing someone with a pen it means it's a parapen, but the code probably didn't factor in people stabbing traitors with their own PDA pens to check if they're parapens or pens in their pockets, and then using the DA to double-check, which is a pretty common strategy for sec when they find someone c4'd in the hallway.
