### ISSUE TITLE
More broken poster description stuff

### ISSUE THREAD

**Issue by ghost** [NTStation/NTstation13#714]
Place any contraband (red) poster on a wall. Description will read:

 That's a poster - Hacking Guide - Error (subtype).
A large piece of space-resistant printed paper. This poster details the internal workings of the common Nanotrasen airlock. This is a bug, please report the circumstances under which you encountered this poster at https://github.com/NTStation/NTstation13/issues.

 That's a poster - Donut Corp. - Error (subtype).
A large piece of space-resistant printed paper. This poster is an advertisement for Donut Corp. This is a bug, please report the circumstances under which you encountered this poster at https://github.com/NTStation/NTstation13/issues.

Name is broken as well

**Comment by RemieRichards** [comment]
@JStheguy

**Comment by ike709** [comment]
This was fixed pls close.
