### ISSUE TITLE
Server still automuting at roundstart

### ISSUE THREAD

**Issue by ghost** [NTStation/NTstation13#722]
@giacom @giacom @giacom @giacom @giacom @giacom 

help

https://github.com/NTStation/NTstation13/pull/707/files

this didn't fix it

**Comment by Giacom** [comment]
Ask SoS to put it on the server config.

**Comment by Giacom** [comment]
>not a bug

**Comment by Atskadan** [comment]
pretty sure SoS' config files are not a bug

**Comment by Neerti** [comment]
I thought this was fixed.

**Comment by ghost** [comment]
Is it?

**Comment by ghost** [comment]
YEAH IT IS
