### ISSUE TITLE
R&D consoles and machines breaking

### ISSUE THREAD

**Issue by Tokiko1** [NTStation/NTstation13#732]
Using a screwdriver on the protolathe(to upgrade it for example) while it is busy constructing queued items will break the console and leave you unable to print anything else. 

Even "reseting" the console by using the screwdriver on it twice will still leave you unable to print anything. This will also sometimes causes some of the other machines to refuse being recognized by a device scan until you reset them aswell. There's probably a whole lot more bugs related to this.

**Comment by ike709** [comment]
This is also a runtime error btw.

**Comment by RemieRichards** [comment]
We need the runtime to solve it then.

**Comment by ike709** [comment]
runtime error: Cannot read null.hacked
proc name: build (/obj/machinery/computer/rdconsole/proc/build)
  source file: rdconsole.dm,218
  usr: Leilani Coldsmith (/mob/living/carbon/human)
  src: Core R&D Console (/obj/machinery/computer/rdconsole/core)
  call stack:
Core R&D Console (/obj/machinery/computer/rdconsole/core): build("basic_matter_bin", 10)

**Comment by RemieRichards** [comment]
Right then, something like the console or one of it's components went null and there was no sanity check.

**Comment by ike709** [comment]
Would fix if knew how.

**Comment by RemieRichards** [comment]
Somewhere in the code, around the line 218 (says so in Runtime) there will be an if(SOMETHING.variable) check, where it needs to be a if(SOMETHING && SOMETHING.variable) check

**Comment by ike709** [comment]
@RemieRichards Me and SirBayer have been trying to fix this for a while, sanity check just makes the runtime a different line, and their is already a sanity check a bit earlier in the code. EDIT: Think we have a fix, gonna test it.
