### ISSUE TITLE
Non-admins can call crew transfer shuttle votes at any time.

### ISSUE THREAD

**Issue by ghost** [NTStation/NTstation13#759]
I believe this has something to do with the fact that bay uses a different (older) permissions thing, and while as an admin the vote says (disallowed) as in normal players should not be able to choose it, it's startable at any time, including lobby. Of course the shuttle doesn't actually come if the vote is started or anything, but this is meant to be an automated or admin-only process and I'm not sure where to go about fixing this. I guess I'll look at gamemode votes since those are disallowed by default.

**Comment by Atskadan** [comment]
theres plenty of admin-only verbs you can look at for examples on how to make them admin only.
