### ISSUE TITLE
H/E (Heat Exchange) pipes just disappear when wrenched.

### ISSUE THREAD

**Issue by LandoTheClimber** [NTStation/NTstation13#775]
![my2uffn](https://cloud.githubusercontent.com/assets/2679005/3451001/ce605c2c-0189-11e4-9c7d-732f5e9e977a.png)
these thingies don't behave, they just vanish from existence, even in the right-click/alt stat menu

**Comment by ChangelingRain** [comment]
They have to be next to other H/E pipes, otherwise they get deleted instantly.

**Comment by LandoTheClimber** [comment]
Whoops, ok.
