### ISSUE TITLE
Assistant registration broken!

### ISSUE THREAD

**Issue by ghost** [NTStation/NTstation13#802]
https://github.com/NTStation/NTstation13/pull/411

This was broken by niggles' /tg/ merge.

But I am working on a fix.

And I still love miggles for doing the /tg/ merge.

**Comment by ike709** [comment]
I never knew it was ever a thing in the first place so...

**Comment by ghost** [comment]
Essentially scanning an assistant's ID with your own will give them basic departmental access to your department. However, it seems to be broken and I can't seem to fix it.

**Comment by ike709** [comment]
Yell at miggles until it works again

**Comment by ghost** [comment]
Nah, I found the real culprit. Neerti attempted to fix it but faaaailed. I'm working on a real fix plus an additional feature for it since it's rather tedious.
