### ISSUE TITLE
simple_animals and disposals.

### ISSUE THREAD

**Issue by Spacemanspark** [NTStation/NTstation13#809]
Simple animals that are disposaled cannot see where they are going until they reach the other end. You should be able to see the tunnel as you're going through it. Not a big, heavy issue, but something that could be looked at. I made a video on how to reproduce this here: https://www.youtube.com/watch?v=x6hEDYm3jm4 .

**Comment by Atskadan** [comment]
@RemieRichards what did you do to the camera

**Comment by RemieRichards** [comment]
Absolutely nothing, any camera based bugs with drones are the fault of Simple_animals or an incorrect piece of code connecting simple_animals to simple_animal/drone.

**Comment by Atskadan** [comment]
i figured it was something fucked up with simple animals
someone test what happens if you play as a goat or something and get disposaled

**Comment by ike709** [comment]
@Atskadan I tried this as a corgi and a carp and it had the same problem so this must be something with simple_animal.dm

**Comment by ghost** [comment]
Change the title to simple animals and disposals then pls
