### ISSUE TITLE
teleporters don't work

### ISSUE THREAD

**Issue by Tokiko1** [NTStation/NTstation13#824]
How to reproduce:
1. Set up a teleporter.
2. Configure it.
3. Turn it on.
4. Notice that the sprite changes, indicating that it's active.
5. Try to step into the teleporter and realize that it's impossible to enter it.

Note that if you set up the teleporter and use a hand teleporter to lock onto its destination it works fine. Maybe related to the recent flyperson changings?

**Comment by Tokiko1** [comment]
After looking through the code, it indeed looks like the flyfication removal broke it. Needs 3 lines readded.

**Comment by Atskadan** [comment]
https://github.com/NTStation/NTstation13/compare/6ce91306c237...6fbfee453e44

this is what it needed, right
should be fixed now

**Comment by RemieRichards** [comment]
Miggles Fixed it.
