### ISSUE TITLE
That's a poster - Tools - Error (subtype/pre-placed poster serial_number generator).

### ISSUE THREAD

**Issue by Limeliz** [NTStation/NTstation13#838]
There are bugged posters in telesci maint tunnels:

"That's a poster - Tools - Error (subtype/pre-placed poster serial_number generator).
A large piece of space-resistant printed paper. This poster is an advertisement for tools. This is a bug, please report the circumstances under which you encountered this poster at https://github.com/NTStation/NTstation13/issues."

and

" That's a poster - Fun Police - Error (subtype/pre-placed poster serial_number generator).
A large piece of space-resistant printed paper. A poster condemning the station's security forces. This is a bug, please report the circumstances under which you encountered this poster at https://github.com/NTStation/NTstation13/issues."

Posters in maintenance tunnels SE of telesci on Metastation.

Server revision: 2014-07-14 6246c9ac0175df6c54210503061aabe01873de58
Server/Map: Arytum / MetaStation

**Comment by Limeliz** [comment]
All posters sitting in maintenance tunnels seem to have this bug. Found four so far (same tunnel as before and also north of arrivals)

**Comment by WJohn** [comment]
All the posters on my away mission also have this exact bug.

**Comment by RemieRichards** [comment]
Do the posters lack an icon? because I'm thinking this might not be a bug, but bad code designed to point out a bug.

These:

> Error (subtype/pre-placed poster serial_number generator).

Bugged posters specifically

Basically I'm asking, "is the only bug that the posters have these extra lines of text?"

**Comment by Limeliz** [comment]
They have different icons, they look all normal except for that weird name and examine-text.

**Comment by RemieRichards** [comment]
So the text is the only issue? because if it is, I've got this solved.

**Comment by Limeliz** [comment]
Seems like it.

**Comment by RemieRichards** [comment]
Alright, Mental note for myself and anyone to beat me to it:

This "bug" is literally that

```
else 
    "blah blah an error occured" 
```

Is not needed, that's the bug, gameover remove the message, and ONLY the one at the bottom of the entire thing, the ones mentioning exact subtypes, like 1 or 0 are fine error messages.
