### ISSUE TITLE
Kinetic accelerator blast adds a black overlay to sand tiles.

### ISSUE THREAD

**Issue by Hatfish** [NTStation/NTstation13#860]
Revision: Metastation 2014-07-21

Problem Description: A nameless black overlay is added on top of sand tiles when a kinetic accelerator is fired nearby.

What did you expect to happen? The sand would remain unchanged

What happened instead? The tile changed color and lost its name.

Why is this bad/What are the consequences? It looks ugly as sin.

Steps to reproduce the problem:
1- Find a secret room with a facehugger on the mining asteroid.

2- Fire a proto-kinetic accelerator near (not directly at) any of the white sand tiles.

3- The tile now has no name or color.

**Comment by ACCount12** [comment]
The fix is removal of beach sand in facehugger rooms. Not sure why there was beach sand, not asteroid sand.
