### ISSUE TITLE
Laser never displays empty laser icon

### ISSUE THREAD

**Issue by ACCount12** [NTStation/NTstation13#892]
1. Spawn a regular laser.
2. Shot all it charges into the wall.
3. Laser icon looks like there is some charge left

Reason: shot cost is 83, power cell charge is 1000. 1000 - 83*12 = 4, so there is 4 charge left in cell. Not sure how to fix this.

**Comment by Tokiko1** [comment]
Maybe have the icon change to empty when a guns remaining energy is lower than the amount of energy it requires to fire it? That should work for all other display based guns, shouldn't it?
