### ISSUE TITLE
gloves not appearing on the body

### ISSUE THREAD

**Issue by Tokiko1** [NTStation/NTstation13#907]
Likely related to dismemberment. Gloves don't show up on your character.

**Comment by RemieRichards** [comment]
did you have both arms?
 if you only had 1 arm, then it's not a bug.

**Comment by Tokiko1** [comment]
Both arms.

**Comment by RemieRichards** [comment]
Welcome to dismemberment, where I'm tired and the checks are probably inverted, please, enjoy your stay!

**Comment by ike709** [comment]
So now we need mob sprites for only one gloves?

**Comment by RemieRichards** [comment]
we could do with them, but right now I'm getting away with rendering the gloves if BOTH hands exist, otherwise they're not visible.

**Comment by Atskadan** [comment]
would it be possible to just have one glove sprite for each direction and flip it so there doesnt need to be a stupid amount of glove sprites

**Comment by RemieRichards** [comment]
#928 Fixes this
