### ISSUE TITLE
using the give verb on people with a missing arm let's them hold said item

### ISSUE THREAD

**Issue by Tokiko1** [NTStation/NTstation13#910]
Title is very self explaining.

How to reproduce the bug:
1. Remove someone's arm.
2. Let them pick up something with their remaining arm.
3. Give them an item.
4. Notice that they are holding two items.

Probably works with no arms aswell.

**Comment by RemieRichards** [comment]
Fucking Give verb, I didn't exist when I wrote dismemberment.

**Comment by RemieRichards** [comment]
Fixed
